site :opscode

cookbook "apache2", git: "git@github.com:hokkai7go/cookbooks.git", rel: "apache2"
cookbook "build-essential", git: "git@github.com:hokkai7go/cookbooks.git", rel: "build-essential"
cookbook "byobu", git: "git@github.com:hokkai7go/cookbooks.git", rel: "byobu"
cookbook "chef_gem", git: "git@github.com:hokkai7go/cookbooks.git", rel: "chef_gem"
cookbook "coreutils", git: "git@github.com:hokkai7go/cookbooks.git", rel: "coreutils"
cookbook "curl", git: "git@github.com:hokkai7go/cookbooks.git", rel: "curl"
cookbook "git-core", git: "git@github.com:hokkai7go/cookbooks.git", rel: "git-core"
cookbook "git-svn", git: "git@github.com:hokkai7go/cookbooks.git", rel: "git-svn"
cookbook "heroku-toolbelt", git: "git@github.com:hokkai7go/cookbooks.git", rel: "heroku-toolbelt"
cookbook "libavahi-common3", git: "git@github.com:hokkai7go/cookbooks.git", rel: "libavahi-common3"
cookbook "libcurl4-openssl-dev", git: "git@github.com:hokkai7go/cookbooks.git", rel: "libcurl4-openssl-dev"
cookbook "libpq-dev", git: "git@github.com:hokkai7go/cookbooks.git", rel: "libpq-dev"
cookbook "mkswap", git: "git@github.com:hokkai7go/cookbooks.git", rel: "mkswap"
cookbook "mosh", git: "git@github.com:hokkai7go/cookbooks.git", rel: "mosh"
cookbook "mysql", git: "git@github.com:hokkai7go/cookbooks.git", rel: "mysql"
cookbook "newrelic", git: "git@github.com:hokkai7go/cookbooks.git", rel: "newrelic"
cookbook "nginx", git: "git@github.com:hokkai7go/cookbooks.git", rel: "nginx"
cookbook "ohai", git: "git@github.com:hokkai7go/cookbooks.git", rel: "ohai"
cookbook "openssl", git: "git@github.com:hokkai7go/cookbooks.git", rel: "openssl"
cookbook "php", git: "git@github.com:hokkai7go/cookbooks.git", rel: "php"
cookbook "postgresql84", git: "git@github.com:hokkai7go/cookbooks.git", rel: "postgresql84"
cookbook "python", git: "git@github.com:hokkai7go/cookbooks.git", rel: "python"
cookbook "rvm", git: "git@github.com:hokkai7go/cookbooks.git", rel: "rvm"
cookbook "td-agent", git: "git@github.com:hokkai7go/cookbooks.git", rel: "td-agent"
cookbook "td", git: "git@github.com:hokkai7go/cookbooks.git", rel: "td"
cookbook "timezone", git: "git@github.com:hokkai7go/cookbooks.git", rel: "timezone"
cookbook "tomcat6", git: "git@github.com:hokkai7go/cookbooks.git", rel: "tomcat6"
cookbook "vim", git: "git@github.com:hokkai7go/cookbooks.git", rel: "vim"
cookbook "xml", git: "git@github.com:hokkai7go/cookbooks.git", rel: "xml"
cookbook "yum", git: "git@github.com:hokkai7go/cookbooks.git", rel: "yum"
cookbook "zsh", git: "git@github.com:hokkai7go/cookbooks.git", rel: "zsh"

